cdp compatibility added

diff --git a/workflow/scripts/hput b/workflow/scripts/hput
--- a/workflow/scripts/hput
+++ b/workflow/scripts/hput
@@ -38,6 +38,16 @@ if [ ! -p "$lFile" ] && [ ! -r "$lFile" -o ! -s "$lFile" ];then
 	exit 1
 fi	
 
+# Dual replication!
+cdpFile=$(basename "$hFile")
+cdpTable=$(basename $(dirname "$hFile"))
+cdpHost="svc_dvd_clarity@cdp-client-01.biotech.cdc.gov"
+cdpCache=/groups/NCIRD/DVD/data/snakemake-cache
+scp "$lFile" "$cdpHost:$cdpCache/$cdpTable/$cdpFile" >/dev/null 2>&1 \
+    && ssh "$cdpHost" "touch $cdpCache/$cdpTable/${cdpFile}.NEW" >/dev/null 2>&1 \
+    || echo "SCP to CDP failed!" 1>&2
+
+# Business as Usual
 if [ "$hLocal" -eq "1" ];then
 	ssh $hLogin "hdfs dfs -put -f $lFile $hFile" >/dev/null 2>&1
 else
